/**
 * Config.gs — constants and Script Properties access.
 *
 * Script Properties (set in GAS UI: Project Settings → Script Properties):
 *   TELEGRAM_BOT_TOKEN  — from @BotFather
 *   GEMINI_API_KEY      — from Google AI Studio
 *   SPREADSHEET_ID      — optional: overrides the container-bound spreadsheet
 *   ALLOWED_USER_IDS    — comma-separated Telegram user IDs (empty = bot tells
 *                         the sender their ID so it can be added)
 *   WEBAPP_URL          — web app deployment URL (used by setWebhook())
 *   WEBHOOK_SECRET      — auto-generated by setWebhook(); doPost rejects
 *                         requests without ?token=<secret>
 */

const CONFIG = {
  DEFAULT_TIMEZONE: 'Asia/Bishkek',
  DEFAULT_LANGUAGE: 'ru',

  // Fallback chain hard cap: one request never tries more models than this.
  MAX_MODEL_ATTEMPTS: 5,

  // Telegram hard limit is 4096. Splitting happens BEFORE HTML conversion,
  // so the split length leaves headroom for entity expansion (& → &amp;).
  TELEGRAM_MAX_LENGTH: 4096,
  TELEGRAM_SPLIT_LENGTH: 3500,

  // Scheduler trigger interval (informational; used by setupTrigger()).
  SCHEDULER_INTERVAL_MINUTES: 10,

  // Skip re-sending a reminder attempted within this window. Must be LARGER
  // than the trigger interval — it also paces retries of failed sends.
  DUPLICATE_SEND_GUARD_MS: 15 * 60 * 1000,

  // Model failure counters older than this are forgotten, so a healthy
  // high-priority model returns to the front of the fallback chain.
  MODEL_FAIL_TTL_MS: 60 * 60 * 1000,

  // Voice files larger than this are declined: 12MB binary → ~16MB base64,
  // safely under Gemini's ~20MB inline request limit.
  MAX_VOICE_FILE_BYTES: 12 * 1024 * 1024,

  // Models sheet cache TTL (seconds).
  MODELS_CACHE_TTL: 300,

  // Seed rows for the Models sheet (free-tier models, current as of 08.2026;
  // edit the Models sheet — not this file — to change the chain).
  DEFAULT_MODELS: [
    { name: 'gemini-3.5-flash-lite', text: true, audio: true, priority: 1 },
    { name: 'gemini-3.1-flash-lite', text: true, audio: true, priority: 2 },
    { name: 'gemini-2.5-flash-lite', text: true, audio: true, priority: 3 },
    { name: 'gemini-3.5-flash',      text: true, audio: true, priority: 4 },
    { name: 'gemini-3.6-flash',      text: true, audio: true, priority: 5 },
    { name: 'gemini-2.5-flash',      text: true, audio: true, priority: 6 }
  ]
};

const SHEETS = {
  REMINDERS: 'Reminders',
  TASKS: 'Tasks',
  USERS: 'Users',
  LOGS: 'Logs',
  MODELS: 'Models'
};

function getProp_(key) {
  return PropertiesService.getScriptProperties().getProperty(key);
}

function getRequiredProp_(key) {
  const value = getProp_(key);
  if (!value) throw new Error('Missing Script Property: ' + key);
  return value;
}

function getBotToken_() { return getRequiredProp_('TELEGRAM_BOT_TOKEN'); }
function getGeminiKey_() { return getRequiredProp_('GEMINI_API_KEY'); }

function getAllowedUserIds_() {
  const raw = getProp_('ALLOWED_USER_IDS') || '';
  return raw.split(',').map(function (s) { return s.trim(); }).filter(String);
}
